"""Public normalized models used across MacWise interfaces."""

from macwise.models.analysis import (
    BackupStatus,
    ClaimBasis,
    Finding,
    FindingTopic,
    PathEvidence,
    StartupKind,
    StartupRecord,
    UsageLabel,
    stable_path_evidence_id,
    stable_startup_id,
)
from macwise.models.audit import AuditDocument, CollectorState, CollectorStatus
from macwise.models.checkup import CheckupPriority, CheckupSummary
from macwise.models.evidence import Evidence, Reliability
from macwise.models.execution import (
    ActionObservation,
    ActionState,
    ExecutionAction,
    ExecutionRun,
    ExecutionState,
    InverseIntent,
    InverseKind,
    VerificationState,
)
from macwise.models.overlap import (
    CatalogAssessment,
    GuardedRecommendation,
    LearningValue,
    OverlapCategory,
    OverlapRelation,
    RecommendationAction,
    stable_overlap_id,
    stable_recommendation_id,
)
from macwise.models.plan import (
    PlanActionKind,
    PlanCandidate,
    PlanDocument,
    PlanEligibility,
    PlannedAction,
    PreflightCheck,
    PreflightKind,
    PreflightOutcome,
    RollbackBlueprint,
    RollbackFeasibility,
    stable_plan_component_id,
)
from macwise.models.score import MacWiseScorecard, ScoreComponent
from macwise.models.software import EntityType, InstallRole, SoftwareRecord, stable_software_id
from macwise.models.storage import StorageLocation, VolumeRecord, stable_volume_id

__all__ = [
    "ActionObservation",
    "ActionState",
    "AuditDocument",
    "BackupStatus",
    "CatalogAssessment",
    "CheckupPriority",
    "CheckupSummary",
    "ClaimBasis",
    "CollectorState",
    "CollectorStatus",
    "EntityType",
    "Evidence",
    "ExecutionAction",
    "ExecutionRun",
    "ExecutionState",
    "Finding",
    "FindingTopic",
    "GuardedRecommendation",
    "InstallRole",
    "InverseIntent",
    "InverseKind",
    "LearningValue",
    "MacWiseScorecard",
    "OverlapCategory",
    "OverlapRelation",
    "PathEvidence",
    "PlanActionKind",
    "PlanCandidate",
    "PlanDocument",
    "PlanEligibility",
    "PlannedAction",
    "PreflightCheck",
    "PreflightKind",
    "PreflightOutcome",
    "RecommendationAction",
    "Reliability",
    "RollbackBlueprint",
    "RollbackFeasibility",
    "ScoreComponent",
    "SoftwareRecord",
    "StartupKind",
    "StartupRecord",
    "StorageLocation",
    "UsageLabel",
    "VerificationState",
    "VolumeRecord",
    "stable_overlap_id",
    "stable_path_evidence_id",
    "stable_plan_component_id",
    "stable_recommendation_id",
    "stable_software_id",
    "stable_startup_id",
    "stable_volume_id",
]
